// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkwoaxntxsumnfdzjnqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrd29heG50eHN1bW5mZHpqbnFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjEwNTcsImV4cCI6MjA2NTUzNzA1N30.Peiuvf0uxQ8GYkkA7wkyHOtn5nuvWqMmJpt3RT3gevs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);